#!/bin/sh

# --step 1
#
# 30 second averages for the last 48 hours
# RRA:AVERAGE:0.5:30:9600

# 24h averages for the last 10 years
# RRA:AVERAGE:0.5:86400:3650

# Max per 24h period for the last 10 years
# RRA:MAX:0.5:86400:3650

rrdtool create /srv/power/garage.rrd --step 1 \
DS:ch1:GAUGE:180:0:U \
DS:ch2:GAUGE:180:0:U \
DS:ch3:GAUGE:180:0:U \
RRA:AVERAGE:0.5:30:9600 \
RRA:AVERAGE:0.5:86400:3650 \
RRA:MAX:0.5:86400:3650

rrdtool create /srv/power/total.rrd --step 1 \
DS:ch1:GAUGE:180:0:U \
RRA:AVERAGE:0.5:30:9600 \
RRA:AVERAGE:0.5:86400:3650 \
RRA:MAX:0.5:86400:3650

