#!/usr/bin/perl -w

my $sensors = [ qw/Garage1 Garage2 Garage3 HouseTotal/ ];
my $rrd = "/srv/power/power.rrd";
my $datadir = "/srv/power";

export_data( "power3h.xml", "3h", 300, $sensors );
export_data( "power24h.xml", "24h", 900, $sensors );
export_data( "power48h.xml", "48h", 1800, $sensors );
export_data( "power1w.xml", "8d", 7200, $sensors );
export_data( "power1m.xml", "1month", 10800, $sensors );
export_data( "power3m.xml", "3month", 43200, $sensors );
export_data( "power1y.xml", "1y", 86400, $sensors );


sub export_data {
    my( $file, $length, $step, $sensors ) = @_;

    my $command = "rrdtool xport -s now-$length --step $step ";

    my $key = ord('a'); 
    foreach my $sensor (@{$sensors}) {
	my $keychar = chr($key);
	$command .= "DEF:$keychar=$rrd:$sensor:AVERAGE " . 
	    "XPORT:$keychar:\"$sensor\" ";
	$key = $key + 1;
    }
    system( "$command > $datadir/$file" );
}

