#!/usr/bin/perl -w

use strict;
use POSIX qw(strftime);
use Data::Dumper;
use IO::Socket::INET;

my $rrd = "/srv/power/power.rrd";

# auto-flush on socket
$| = 1;

while(1) { 
    # create a connecting socket
    my $socket = new IO::Socket::INET (
	PeerHost => 'rpi1',
	PeerPort => '12346',
	Proto => 'tcp',
	);
    
    if( not defined $socket ) {
	print "Failed to connect: $!\n";
	sleep 5;
	next;
    }

    my( $Garage1, $Garage2, $Garage3, $HouseTotal );

    while ( my $line = <$socket> ) {
	my $msg = parse_xml( $line );
	
	my $sensor = $msg->{msg}->{sensor};
	if( not defined $sensor ) {
	    next;
	}

	my $ch1 = 0 + $msg->{msg}->{ch1}->{watts};
	my $ch2 = 0 + $msg->{msg}->{ch2}->{watts} if defined $msg->{msg}->{ch2};
	my $ch3 = 0 + $msg->{msg}->{ch3}->{watts} if defined $msg->{msg}->{ch3};
	
	if( $sensor eq "9" ) {
#	    print "House total: $ch1 W\n";
	    $HouseTotal = $ch1;
	}
	elsif( $sensor eq "0" ) {
#	    print "Garage: $ch1 + $ch2 + $ch3 = " . ($ch1+$ch2+$ch3) . " W\n";
	    $Garage1 = $ch1;
	    $Garage2 = $ch2;
	    $Garage3 = $ch3;
	}
	else {
#	    print "Unknown: " . Dumper( $msg ) . "\n";
	}
	
	if( defined( $HouseTotal ) and defined( $Garage1 ) ) {
	    qx(rrdtool update $rrd N:$Garage1:$Garage2:$Garage3:$HouseTotal);
	}
    }
    $socket->close();
}

sub parse_xml {
    my( $str ) = @_;
    my $result = {};
    die if not defined $str;
    if( $str !~ /</ ) {
	return $str;
    }

    while( length($str) > 2 ) {
	$str =~ s%^\<([a-z0-9]+)\>(.*?)\</\g1\>%%;

	my $tag = $1;
	my $content = $2;
	if( not defined $tag ) {
#	    print "Failed to parse $str\n";
	    return {};
	}
	$result->{$tag} = parse_xml( $content );
    }

    return $result;
}
